// <auto-generated />
using System;
using Cocktails.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cocktails.DbMigrations.Migrations
{
    [DbContext(typeof(CocktailsContext))]
    [Migration("20230916192509_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cocktails.Data.Entities.Cocktail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CocktailCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("FlavorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ModifyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CocktailCategoryId");

                    b.HasIndex("FlavorId");

                    b.ToTable("Cocktail");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.CocktailCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("CocktailCategory");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Modern classic"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Coffee & Dessert"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Shots"
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tropical"
                        },
                        new
                        {
                            Id = 6L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nonalcoholic"
                        });
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Flavor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Flavor");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bitter"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sweet"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sour"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Fruity"
                        });
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Vodka"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Gin"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Rum"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tequila"
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tomato juice"
                        },
                        new
                        {
                            Id = 6L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Lemon juice"
                        });
                });

            modelBuilder.Entity("Cocktails.Data.Entities.MeasureUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeasureUnit");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Oz"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Piece"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Dash"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Cup"
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifyDate = new DateTimeOffset(new DateTime(2023, 9, 16, 19, 25, 9, 92, DateTimeKind.Unspecified).AddTicks(4592), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Shot"
                        });
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Mix", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("CocktailId");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("MeasureUnitId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ModifyDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasureUnitId");

                    b.ToTable("Mix");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Cocktail", b =>
                {
                    b.HasOne("Cocktails.Data.Entities.CocktailCategory", "CocktailCategory")
                        .WithMany("Cocktails")
                        .HasForeignKey("CocktailCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cocktails.Data.Entities.Flavor", "Flavor")
                        .WithMany("Cocktails")
                        .HasForeignKey("FlavorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CocktailCategory");

                    b.Navigation("Flavor");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Mix", b =>
                {
                    b.HasOne("Cocktails.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("Mixes")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cocktails.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("Mixes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cocktails.Data.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany("Mixes")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Ingredient");

                    b.Navigation("MeasureUnit");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Cocktail", b =>
                {
                    b.Navigation("Mixes");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.CocktailCategory", b =>
                {
                    b.Navigation("Cocktails");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Flavor", b =>
                {
                    b.Navigation("Cocktails");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("Mixes");
                });

            modelBuilder.Entity("Cocktails.Data.Entities.MeasureUnit", b =>
                {
                    b.Navigation("Mixes");
                });
#pragma warning restore 612, 618
        }
    }
}
